### ISSUE TITLE
Allow changing of the base URL

### ISSUE THREAD

**Issue by synesthesium** [FujiMakoto/pygelbooru#15]
As it stands, the base URL is hard-coded and cannot be changed. (?)
There are several Gelbooru-based and/or API compatible sites that could make use of this library (such as Safebooru or rule34) that currently cannot be accessed due to the base URL being hard-coded into the Gelbooru class.
Allowing an argument that allows you to set the base URL would be extremely useful.

**Comment by FujiMakoto** [comment]
That's certainly something I can do, I didn't know all of these sites had a compatible API.

I'll do some testing first just to make sure it works as intended then push an update to the library.

**Comment by FujiMakoto** [comment]
Support for this has been added to the v0.5.0 release now!

You can assign a custom API endpoint via the new `api` parameter in the Gelbooru class.
```python
from pygelbooru import Gelbooru
gelbooru = Gelbooru(api='https://safebooru.org/')
results = gelbooru.search_posts(tags=['dog ears', '1girl'], exclude_tags=['nude'])
import asyncio
loop = asyncio.get_event_loop()
r = loop.run_until_complete(results)
```
