### ISSUE TITLE
gelbooru.tag_list(name_pattern=' ') doesn't return matching tags, only the tag itself.

### ISSUE THREAD

**Issue by RafaelLacer** [FujiMakoto/pygelbooru#6]
The title says it all. When trying to search for matching tags, it only returns the tag you entered, if it exists, otherwise, just returns [].
example:
```
from pygelbooru import Gelbooru
import asyncio

async def search_tags():
    gel = Gelbooru()
    results = await gel.tag_list(name_pattern='splatoon', limit=4)
    return results

results = asyncio.run(search_tags())
print(results)
```

Should return:
```
[<GelbooruTag(id=892683, name='splatoon_(series)', count=11353)>,
 <GelbooruTag(id=759189, name='splatoon_2', count=3488)>,
 <GelbooruTag(id=612372, name='aori_(splatoon)', count=2266)>,
 <GelbooruTag(id=612374, name='hotaru_(splatoon)', count=2248)>]
```

Actually returns:
`splatoon`

**Comment by jedi2light** [comment]
There is nothing wrong with the library itself, but with the examples in README.md

Instead of
```
await gelbooru.tag_list(name_pattern='splatoon', limit=4)
```

... you should use
```
await gelbooru.tag_list(name_pattern='%splatoon%', limit=4)
```

... to search all possible tags on Gelbooru 

API says:

```
name_pattern A wildcard search for your query using LIKE. Use _ for single character wildcards or % for multi-character wildcards. (%choolgirl% would act as *choolgirl* wildcard search.)
```

So... shall I create a small patch for README.md?  
Also, this issue can be closed now, I guess.

**Comment by jedi2light** [comment]
Another thing I hate to work with is returning a single GelbooruTag object instead of a list with the single GelbooruTag object. I think developers love it when the function always returns the same type as expected, arent we?

Because the API always returns a list, so shall we also always return a list with even a single tag object?

**Comment by FujiMakoto** [comment]
Fair point, the method is named tag_list so I agree it should always return a list, I'll have this updated in the next release
